// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV4skkdudE8n2VSsnDbwISKA4Pf_vLXWE',
    appId: '1:54317792230:web:3f04c1e992d66a0c5f3427',
    messagingSenderId: '54317792230',
    projectId: 'sample-chat-22b5b',
    authDomain: 'sample-chat-22b5b.firebaseapp.com',
    storageBucket: 'sample-chat-22b5b.appspot.com',
    measurementId: 'G-SZQ8MP43KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwZ9RgKu0Rdsj52x_869AdjyWZruE6mG0',
    appId: '1:54317792230:android:6a9d30f9a64bfc5d5f3427',
    messagingSenderId: '54317792230',
    projectId: 'sample-chat-22b5b',
    storageBucket: 'sample-chat-22b5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOczxMi4jDvO2cuXjV-17BiQBl_8sVfN8',
    appId: '1:54317792230:ios:679fe790baaf1c045f3427',
    messagingSenderId: '54317792230',
    projectId: 'sample-chat-22b5b',
    storageBucket: 'sample-chat-22b5b.appspot.com',
    iosClientId: '54317792230-m4hr2dat1flrgee5dri6juaauug0vov8.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampleChat',
  );
}
